### PR TITLE
Fixes the output parsed by the Code Climate CLI

### LINKED ISSUE #175: How are you using this with codeclimate?
**What do you want to discuss?**

@dkrutskikh, I noticed that you recently updated the reporter. I want to integrate this with the Code Climate Engine but the Code Climate CLI is throwing an exception when using the codeclimate reporter. You can see the exact error in my PR draft here wrike/codeclimate-dart/pull/2 and from my fork here zgosalvez/codeclimate-dart/pull/1.

### PR DESCRIPTION
**Pull request by zgosalvez**
### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Closes #175. I'm not sure how to include tests for this. However, I can verify that this quick-and-dirty fix resolves my issue at zgosalvez/codeclimate-dart/pull/1 when I tried it on my private Flutter project. My issue contains comments describing the problem with the `codeclimate` reporter in that it is not generating the correct output specified at [codeclimate/platform/blob/master/spec/analyzers/SPEC.md#output](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#output).

### What changes did you make? (Give an overview)
Fixed the `codeclimate` reporter, which couldn't be read by the [Code Climate CLI](https://github.com/codeclimate/codeclimate) as shown in wrike/codeclimate-dart/pull/2.

### Is there anything you'd like reviewers to focus on?
The [wrike/codeclimate-dart](https://github.com/wrike/codeclimate-dart/) repository is very silent. I'm attempting to submit my fork to the [list of engines](https://docs.codeclimate.com/docs/list-of-engines) on Code Climate, so any help to get the dart engine on the list and working is appreciated.

### CODE REVIEW

**Comment by dkrutskikh** [comment]
@zgosalvez please try to check version from `codeclimate` branch of my fork git@github.com:dkrutskikh/dart-code-metrics.git

**Comment by zgosalvez** [comment]
@dkrutskikh, I rebuilt the engine using your branch/fork and it works/analyzes successfully on my private Flutter project. 🚀

**Comment by dkrutskikh** [comment]
@zgosalvez can you contribute documentation how to setup codeclimate for open source Flutter projects?

**Comment by zgosalvez** [comment]
> @zgosalvez can you contribute documentation how to setup codeclimate for open source Flutter projects?

I don't recommend adding it just yet. We'll need to have my fork [zgosalvez/codeclimate-dart](https://github.com/zgosalvez/codeclimate-dart/pull/1) or the upstream [wrike/codeclimate-dart](https://github.com/wrike/codeclimate-dart) reviewed first, then officially included in the Code Climate's list of engines. Would you know if [wrike/codeclimate-dart](https://github.com/wrike/codeclimate-dart) is maintained? No one has responded to me there so I'm close to submitting my fork instead.

**Comment by zgosalvez** [comment]
@dkrutskikh, I noticed that #177 has been merged but no release has been made yet. When can I expect the release? FYI, I tested again on `master` and it still works.

Also, any idea if [wrike/codeclimate-dart](https://github.com/wrike/codeclimate-dart) is still active? Otherwise, I'll submit my fork to Code Climate instead.

**Comment by zgosalvez** [comment]
I'm closing this PR since the fix has been merged via #177, and that [wrike/codeclimate-dart](https://github.com/wrike/codeclimate-dart) has been maintained.

**Pull request closed without merging**
